name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - name: Installar JDK 21
        uses: actions/setup-java@v5.0.0
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Compilar api
        run: mvn clean install -DskipTests -B

      - name: Construir imagen de docker
        run: docker build -t vuelos-api:latest .

      - name: Subir la imagen a dockerhub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker tag vuelos-api:latest ${{ secrets.DOCKERHUB_USERNAME }}/vuelos-api:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/vuelos-api:latest

  deploy-test:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - name: Desplegar en entorno de pruebas
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/vuelos-api:latest
            docker stop vuelos-api || true
            docker rm vuelos-api || true
            docker run -d -p 8081:8080 --name vuelos-api ${{ secrets.DOCKERHUB_USERNAME }}/vuelos-api:latest