name: CD en railway

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Instalar la CLI de Railway
        run: npm i -g @railway/cli

      - name: Login en Railway
        run: railway login --token ${{ secrets.RAILWAY_TOKEN }}

      - name: Desplegar
        run: railway up --service api-vuelos